# Generated by Django 5.0.2 on 2024-02-20 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_member_created_date_member_updated_date'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_created',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_updated',
            new_name='updated_date',
        ),
        migrations.AddField(
            model_name='post',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='member.member'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='post_content',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_title',
            field=models.CharField(max_length=50),
        ),
    ]
