# Generated by Django 5.0.2 on 2024-02-22 08:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0002_member_created_date_member_updated_date'),
        ('post', '0002_rename_post_created_post_created_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reply_content', models.CharField(max_length=100)),
                ('group', models.IntegerField(default=0)),
                ('depth', models.IntegerField(default=0)),
                ('secret', models.CharField(choices=[('Y', '비공개'), ('N', '공개')], default='N', max_length=20)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='member.member')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='post.post')),
            ],
            options={
                'db_table': 'tbl_reply',
                'ordering': ['-id'],
            },
        ),
    ]
